### ISSUE TITLE
React version

### ISSUE THREAD

**Issue by sanzhardanybayev** [AmurKhoyetsyan/X-Ray#1]
Hello! You did an amazing job! 
Can you make in React?

**Comment by AmurKhoyetsyan** [comment]
Hello! Yes I can. Soon it will be.

**Comment by AmurKhoyetsyan** [comment]
https://www.npmjs.com/package/reactjs-x-ray
npm i reactjs-x-ray

**Comment by AmurKhoyetsyan** [comment]
https://www.npmjs.com/package/react-js-x-ray
npm i react-js-x-ray

**Comment by sanzhardanybayev** [comment]
@AmurKhoyetsyan nice, thanks a lot!!!
